In [2]:
# Import dependency 
import numpy as np 
import torch 
import torch.optim as optim
import torch.nn as nn 

In [3]:
# Data generation 
true_b = 1
true_w = 2 
N = 100

# set the random seed for numpy 
np.random.seed(43)

x= np.random.rand(N,1)
epsilon = (.1 * np.random.rand(N,1))

y = true_b + true_w *x + epsilon

In [4]:
#Generate training and validating sets
idx = np.arange(N)

# Use first 80 random indices for train 
train_idx = idx[:int(N*.8)]
val_idx = idx[int(N*.8):]

# Generate train and validation sets
x_train, y_train = x[train_idx], y[train_idx]


In [5]:
# Data preparation 

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Transform data from numpy array to torch tensor
x_train_tensor = torch.as_tensor(x_train).float().to(device)
y_train_tensor = torch.as_tensor(y_train).float().to(device)

In [6]:
# Build a Dataset
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self, x_tensor, y_tensor):
        self.x = x_tensor
        self.y = y_tensor
    
    def __getitem__(self, index):
        return (self.x[index], self.y[index])
    
    def __len__(self):
        return len(self.x)

train_data = CustomDataset(x_train_tensor, y_train_tensor)
print(train_data[0])

(tensor([0.1151]), tensor([1.2404]))


In [55]:
#Define the train step

def make_train_step(model, loss_fn, optimizer):
    # Builds function that performs a step in the train loop 
    def perform_train_step(x,y):
        
        # Set the model to TRAIN mode
        model.train()
        
        # Step1: Compute the model's predicition - forward pass
        yhat = model(x)
        
        # Step2: Compute the loss
        loss = loss_fn(yhat, y)
        
        # Step3: Compute gradients for "b" and "w" parameters
        loss.backward()
        
        # Step4: Updates parameters using gradients and the learning rate
        optimizer.step()
        optimizer.zero_grad()
        
        print(model.state_dict())
        # Return the loss 
        return loss.item()
    #Return the function that will be called inside the train loop
    return perform_train_step

In [56]:
# Model config 

# Define the model 
class ManualLinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)
    def forward(self,x):
        return self.linear(x)


# Set learning rate 
lr = 0.1

torch.manual_seed(42)

# Create a model and send it to the device 
model = ManualLinearRegression().to(device)
print(model.state_dict())

# Define a SGD optimizer to update the parameters 
optimizer = torch.optim.SGD(model.parameters(), lr=lr)

# Define a MSE loss function 
loss_fn = nn.MSELoss(reduction="mean")


# Create a train_step 
train_step = make_train_step(model, loss_fn, optimizer)

OrderedDict([('linear.weight', tensor([[0.7645]])), ('linear.bias', tensor([0.8300]))])


In [57]:
# Model training

n_epochs = 1000
losses = []
for epoch in range(n_epochs):
    loss = train_step(x_train_tensor, y_train_tensor)

   

OrderedDict([('linear.weight', tensor([[0.8715]])), ('linear.bias', tensor([1.0004]))])
OrderedDict([('linear.weight', tensor([[0.9537]])), ('linear.bias', tensor([1.1258]))])
OrderedDict([('linear.weight', tensor([[1.0175]])), ('linear.bias', tensor([1.2177]))])
OrderedDict([('linear.weight', tensor([[1.0675]])), ('linear.bias', tensor([1.2847]))])
OrderedDict([('linear.weight', tensor([[1.1073]])), ('linear.bias', tensor([1.3332]))])
OrderedDict([('linear.weight', tensor([[1.1394]])), ('linear.bias', tensor([1.3680]))])
OrderedDict([('linear.weight', tensor([[1.1657]])), ('linear.bias', tensor([1.3925]))])
OrderedDict([('linear.weight', tensor([[1.1878]])), ('linear.bias', tensor([1.4094]))])
OrderedDict([('linear.weight', tensor([[1.2066]])), ('linear.bias', tensor([1.4207]))])
OrderedDict([('linear.weight', tensor([[1.2230]])), ('linear.bias', tensor([1.4278]))])
OrderedDict([('linear.weight', tensor([[1.2375]])), ('linear.bias', tensor([1.4318]))])
OrderedDict([('linear.weight', t

OrderedDict([('linear.weight', tensor([[1.9820]])), ('linear.bias', tensor([1.0605]))])
OrderedDict([('linear.weight', tensor([[1.9822]])), ('linear.bias', tensor([1.0604]))])
OrderedDict([('linear.weight', tensor([[1.9824]])), ('linear.bias', tensor([1.0603]))])
OrderedDict([('linear.weight', tensor([[1.9826]])), ('linear.bias', tensor([1.0602]))])
OrderedDict([('linear.weight', tensor([[1.9828]])), ('linear.bias', tensor([1.0601]))])
OrderedDict([('linear.weight', tensor([[1.9830]])), ('linear.bias', tensor([1.0599]))])
OrderedDict([('linear.weight', tensor([[1.9832]])), ('linear.bias', tensor([1.0598]))])
OrderedDict([('linear.weight', tensor([[1.9834]])), ('linear.bias', tensor([1.0597]))])
OrderedDict([('linear.weight', tensor([[1.9836]])), ('linear.bias', tensor([1.0596]))])
OrderedDict([('linear.weight', tensor([[1.9838]])), ('linear.bias', tensor([1.0595]))])
OrderedDict([('linear.weight', tensor([[1.9840]])), ('linear.bias', tensor([1.0594]))])
OrderedDict([('linear.weight', t

OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', tensor([[1.9991]])), ('linear.bias', tensor([1.0512]))])
OrderedDict([('linear.weight', t

OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])
OrderedDict([('linear.weight', t

In [33]:
# Model's parameter before training 
print(model.state_dict())

OrderedDict([('linear.weight', tensor([[1.9994]])), ('linear.bias', tensor([1.0510]))])


In [30]:
# Check model's parameters
#print(model.state_dict())

In [31]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([1.0510], requires_grad=True)]
