In [1]:
import torch

In [5]:
torch.manual_seed(100)

In [6]:
b = torch.randn(1, requires_grad=True, dtype=torch.float)

In [7]:
b

tensor([0.3607], requires_grad=True)

In [8]:
import torch 

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Step 0 - initializes parameters "b" and "w" randomly
# Set the random number seed for CPU
torch.manual_seed(42)

b = torch.randn(1,requires_grad=True, dtype=torch.float, device=device)
w = torch.randn(1, requires_grad=True, dtype=torch.float, device=device)

print(b, w)

tensor([0.3367], requires_grad=True) tensor([0.1288], requires_grad=True)


In [20]:
import numpy as np
idx = np.arange(3)
idx

x = np.random.rand(10, 1)
print(x)
print(x[[0,2,3]])

[[0.65256772]
 [0.22165112]
 [0.14159176]
 [0.85059477]
 [0.70207745]
 [0.20589596]
 [0.05378338]
 [0.43089977]
 [0.06931514]
 [0.47344498]]
[[0.65256772]
 [0.14159176]
 [0.85059477]]
